language: cpp

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
    - os: osx
      language: objective-c
  env:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

global:
  env:
    - APM_TEST_PACKAGES=""
    - CHROME_DEVEL_SANDBOX=""
